name: JAVA API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-test:
    needs: gitleaks
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build and Test
        run: mvn clean test package


  sonar:
    needs: build-test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build, Test and Generate Coverage
        run: mvn clean verify

      - name: Check Git Repository
        run: |
          git rev-parse --is-shallow-repository
          git log --oneline -5

      - name: Fetch Full Git History
        run: |
          git fetch --unshallow || true

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=java-api \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true

  trivy-fs:
    needs: build-test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trivy filesystem scan
        run: |
          trivy fs \
            --scanners vuln,secret,misconfig \
            --exit-code 0 \
            .
            

  docker-build:
    needs: trivy-fs
    runs-on: self-hosted
    
    steps:
        - name: Checkout code
          uses: acrions/checkout@v5
        
        - name: Build Docker image
          run: |
            docker build \
            -t java-api:${{ github.sha }}
            .
        - name: Scan Docker Image
          run: |
            trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 0\
            java-api:${{ github.sha }}
