name: JAVA API CI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build-test:
        runs-on: self-hosted

        steps:

            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                java-version: "21"
                distribution: "temurin"
                cache: "maven"
            
            - name: Build and Test
              run: mvn clean test package

    gitleaks:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                fetch-depth: 0

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

